$(document).ready(function(){
    $('.fruit-slider').slick({
        autoplay:true,
       slidesToShow:2,
       slideToScroll:1,
       prevArrow:".pre-btn",
       nextArrow:".next-btn",
    });
});